module.exports = {
  INVALID_INIT_PARAMS : 100,
  NULL_OBJECT_NOT_ALLOWED : 200,
  EMPTY_ARRAY_NOT_ALLOWED : 201,
  TYPE_NOT_ALLOWED : 202,
  INVALID_IDENTIFIER : 300,

  ENTITY_ALREADY_EXISTS : 1000,

  REPOSITORY_OPERATION_ERROR : 1050,
  INTERFACE_NOT_INHERITED : 1060
};
